package com.jerboa.api.compat.v0_17_2.types
data class Post(
    val id: PostId,
    val name: String,
    val url: String?,
    val body: String?,
    val creator_id: PersonId,
    val community_id: CommunityId,
    val removed: Boolean,
    val locked: Boolean,
    val published: String,
    val updated: String?,
    val deleted: Boolean,
    val nsfw: Boolean,
    val embed_title: String?,
    val embed_description: String?,
    val thumbnail_url: String?,
    val ap_id: String,
    val local: Boolean,
    val embed_video_url: String?,
    val language_id: LanguageId,
    val featured_community: Boolean,
    val featured_local: Boolean,
)
