package com.jerboa.api.compat.v0_17_2.types
data class SaveUserSettings(
    val show_nsfw: Boolean?,
    val show_scores: Boolean?,
    val theme: String?,
    val default_sort_type: SortType?,
    val default_listing_type: ListingType?,
    val interface_language: String?,
    val avatar: String?,
    val banner: String?,
    val display_name: String?,
    val email: String?,
    val bio: String?,
    val matrix_user_id: String?,
    val show_avatars: Boolean?,
    val send_notifications_to_email: Boolean?,
    val bot_account: Boolean?,
    val show_bot_accounts: Boolean?,
    val show_read_posts: Boolean?,
    val show_new_post_notifs: Boolean?,
    val discussion_languages: List<LanguageId>?,
    val generate_totp_2fa: Boolean?,
    val auth: String,
)
